### ISSUE TITLE
Proposed algorithm

### ISSUE THREAD

**Issue by pnrobinson** [monarch-initiative/dsppc#1]
Definitions
1. GPI genes -- the list of genes associated with the GPI enzymes
2. target set - the genes that are modified with a GPI anchor from Leigh's list (https://docs.google.com/spreadsheets/d/1opZrVNZD5eNSLr0AyxmVSGXBLERF4Bg8NhiKrmRzAKs/edit#gid=0)

Hypothesis
The phenotypes that characterize the GPI-gene related diseases, such as Mabry syndrome (https://omim.org/entry/239300), which is caused by mutations in PIGV, are related to defects caused by misfunction of the target genes.

Algorithm
1. Make a set of all HPOs associated with the GPI diseases
-- optionally apply a filter to demand that a phenotype is seen in at least k of the diseases
-- use the function in HpoDisease that returns TermIds (not HpoAnnotation objects)
2. calculate a similarity between the GPI set and the target set
Try two similarity functions
-- for each gene/disease associated with the target set, choose the best matching HPO term (highest IC score), and form the sum 
-- for each gene/disease associated with the target set, take the sum of all matching HPO terms whose IC score exceeds a threshold t.

**Comment by pnrobinson** [comment]
For the GPI genes -> merge all HPOs seen in at least k diseases into one Set.
For the target set -> Do not merge the HPOs into one big set. Instead, if a certain target gene is associated with multiple OMIM diseases, merge all of those HPOs into a set. Keep one such set for each target gene associated with >=1 disease. Ignore target genes associated with no disease.

**Comment by pnrobinson** [comment]
To implement, cf the demos in phenol.
1. Create a ``ResnikSimilarity`` object
2. Create a list of pheno abnormalties for the GPI as above
List<TermId> gpi = ...;
3. For each disease ``D`` in the target set
List<TermId> targetDisease = D.getPhenotypicAbnormalityTermIdList();
double max=-1d;
for (TermId tid : targetDisease) {
  List<TermId> singleEntryList = new ArrayList<>();
singleEntryList.add(tid)
    double similarity = resnikSimilarity.computeScore(gpi,singleEntryList);
if (similarit>max) max=similarity;
/// etc
}

**Comment by hannahblau** [comment]
Per discussion with @pnrobinson 17 December:
skip over any line of mim2gene_medgen that has "nondisease" in final column (no point in logging it)
write diseases related to GPI pathway, GPI anchored genes to two separate files

remove GPI-pathway diseases from the map of diseases before selecting randomized set (can leave the GPI-anchored diseases in the map)
might get duplicate indices so make sure set of diseases has the correct size before you stop choosing random indices
on multiple iterations, it's OK if the same disease winds up more than once in the randomly chosen set

two command line arguments: minimum number of diseases if user wants to filter the phenotypes; threshold for similarity function (default value: 2)
 
@LCCarmody

**Comment by pnrobinson** [comment]
I think we can close this -- all is implemented
